### PR TITLE
facilitate configuration of nomad env

### PR DESCRIPTION
**Pull request by nathwill**
here's a PR presenting an alternate approach to #41 using data bags instead of node attributes. i'm not a fan of putting sensitive data in node attributes, since they get saved back to the server unless you go to non-trivial lengths to blacklist the attribute (or whitelist what gets saved). the approach used in #41 works, but has the aforementioned gotcha for anybody not aware of that limitation. in the interest of making the "right thing" the "easy thing", encouraging data bag use here seems preferable, IMO.

i'm also taking advantage of the opportunity to drop support for upstart, since env configuration in upstart is pretty ugly, and we shouldn't need to deal with that ugliness given: Ubuntu moved away in a stable release in 2016 & CentOS moved away in a stable release in 2014, so I'm fairly confident the intersection of people using legacy distros and distributed scheduler technologies in 2018 is a small one.

### CODE REVIEW

**Comment by dbresson** [comment]
Even better would be to pull the config from node.run_state. That way we're not prescribing exactly how it's stored. That would permit using chef-vault to store the data or whatever else, and then pushing it into run_state as part of a wrapper cookbook recipe.

**Comment by nathwill** [comment]
great observation @dbresson, TIL about node.run_state 👏 .

**Review by dbresson — APPROVED** [review]

**Comment by nathwill** [comment]
shipped in 2.0.0, available on supermarket

**Comment by dbresson** [comment]
Thanks, I'm already using it.

**Pull request merged**
