### PR TITLE
Features for testing, server and agent configs

### PR DESCRIPTION
**Pull request by dsklopp**
I'm sending this in case you find it useful.  I've added a README.  I've added a server.rb and client.rb, the former creates a nomad server, the latter an agent.  The .kitchen.yml was updated to create a cluster of machines, 1 server and 3 agents (clients).  Additionally added some conditional code to handle differences in test-kitchen environments versus production environments.

### CODE REVIEW

**Comment by dsklopp** [comment]
I'll fix the style guide issues and resubmit the PR.

**Comment by nathwill** [comment]
thanks @dsklopp, at first glance, i really like it! i'm gonna take the TK suites for a spin and see how it goes. 

i did notice that Travis is currently failing on chefspec due to the removal of the default recipe; if you could straighten that out, i'd appreciate it. if you have chefdk installed, you can run the chefspec tests via `chef exec rake chefspec`.

**Comment by nathwill** [comment]
actually, don't worry about it. after playing around with this a bit, the server/client recipe stuff isn't anything that isn't already possible in a wrapper cookbook just by using the existing resources, and merging it changes the way this cookbook would be consumed enough that i'd prefer to avoid it.

instead i think i'm going to cherry pick some of the bits out (like the profile.d file) that do add some new features that aren't as disruptive.

thanks again for sharing your changes!

**Comment by dsklopp** [comment]
Apologies I was out at the time and missed this.  A lot has changed in the past few months, so I'll check out your latest branch.

**Pull request closed without merging**
