### PR TITLE
Protect sensitive nomad config files

### PR DESCRIPTION
**Pull request by evan2645**
Many of these config files contain secrets, and the default mode is
world readable. Mark all as sensitive, and not world readable.

It would be nice to see configurable user in this cookbook, but since
everything currently is installed and run as root, user/group
considerations are out of scope for this particular change.

Currently, sensitive data is being leaked to chef output and logs

### CODE REVIEW

**Comment by robottaway** [comment]
Deployed using this branch and can confirm we are no longer leaking Vault tokens when we converge. Also configuration files are no longer able to be read by all users.

**Comment by nathwill** [comment]
👍

**Comment by nathwill** [comment]
hey folks, sorry for the late response on this, somehow the initial PR slipped right past my radar. this is a great improvement, so its been merged and pushed to supermarket in 0.10.1. cheers!

**Comment by robottaway** [comment]
Awesome, thank you Nathan!

**Pull request merged**
